### Testing Server Awaekness
GET http://localhost:3000/

##### USER ROUTES #####
### Create User
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name": "Rabin Gautam",
    "phone": "1234567891",
    "password": "password"
}

### Login User
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "phone": "1234567891",
    "password": "password"
}

### Get All Users
GET http://localhost:3000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MzEzOTY2LCJleHAiOjE3NDA5MDU5NjZ9.7RzpOvGGBYJTars4YJ-RotObGypZZtO245v-h4TOsGs

### Get User By Id
GET http://localhost:3000/api/users/1

### Update User Profile
PUT http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MzEzOTY2LCJleHAiOjE3NDA5MDU5NjZ9.7RzpOvGGBYJTars4YJ-RotObGypZZtO245v-h4TOsGs
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Rabin Gautam
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="phone"
Content-Type: text/plain

1234567891
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lat"
Content-Type: text/plain

23.455
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lon"
Content-Type: text/plain

45.678
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="userProfile"; filename="profile.jpg"
Content-Type: image/jpeg

< C:\Users\USER\Downloads\pp1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get profile picture of user
GET http://localhost:3000/uploads/userProfile-1738314029382.jpg

### Delete User
DELETE http://localhost:3000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM3MjEzMDQ2LCJleHAiOjE3Mzk4MDUwNDZ9.lrk3pn8KMlx6pELLvx2zU7XOWDs1V7zmiMLlwTvYVW0



##### PROVIDER ROUTES #####
### Create Provider
POST http://localhost:3000/api/providers/register
Content-Type: application/json

{
    "name": "Nabin Sah",
    "phone": "1234567895",
    "password": "password",
    "address": "WRC gate, Lamachaur",
    "city": "Pokhara"
}

### Login Provider
POST http://localhost:3000/api/providers/login
Content-Type: application/json

{
    "phone": "1234567895",
    "password": "password"
}

### Get All Providers
GET http://localhost:3000/api/providers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM3MjEzMDQ2LCJleHAiOjE3Mzk4MDUwNDZ9.lrk3pn8KMlx6pELLvx2zU7XOWDs1V7zmiMLlwTvYVW0

### Get Provider By Id
GET http://localhost:3000/api/providers/1

### Update Provider Profile
PUT http://localhost:3000/api/providers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3MjIwODM2LCJleHAiOjE3Mzk4MTI4MzZ9._X6yFsH1Sr6V2A6bOt_bwBYA9z1HiPrPlwx5ZSkpLis
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Rabindra Gautam
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="phone"
Content-Type: text/plain

1234567892
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lat"
Content-Type: text/plain

23.455
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lon"
Content-Type: text/plain

45.678
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="ProviderProfile"; filename="profile.jpg"
Content-Type: image/jpeg

< C:\Users\USER\Downloads\pp1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get profile picture of provider
GET http://localhost:3000/uploads/providerProfile-1737221185104.jpg

### Delete Provider
DELETE http://localhost:3000/api/providers
Authorization: Bearer token_goes_here

##### SERVICE ROUTES #####
### Create Service
POST http://localhost:3000/api/services
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MzE0NDE5LCJleHAiOjE3NDA5MDY0MTl9.YKxqhqUKbXgmvrvDiW0e_yzJA7QbNDBkg0v18golvsY
Content-Type: application/json

{
    "name": "Lamachaur plumbing",
    "description": "Laptop servicing with 40% discount for exam seasion.",
    "mincharge": 500,
    "type": "plumbing"
}

### Get all services
GET http://localhost:3000/api/services

### Get all services of a category/type
GET http://localhost:3000/api/services?type=plumbing

### Get a service
GET http://localhost:3000/api/services/1

### Service Categories
GET http://localhost:3000/api/services/categories

### Update a service
PUT http://localhost:3000/api/services/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3MjIwODM2LCJleHAiOjE3Mzk4MTI4MzZ9._X6yFsH1Sr6V2A6bOt_bwBYA9z1HiPrPlwx5ZSkpLis
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Plumbing
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"
Content-Type: text/plain

The reliable plumbing service around lamachaur.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="mincharge"
Content-Type: text/plain

200
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="type"
Content-Type: text/plain

plumbing
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="serviceImg"; filename="profile.jpg"
Content-Type: image/jpeg

< C:\Users\USER\Downloads\pp1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Delete a service
DELETE http://localhost:3000/api/services/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM3Nzg5MDc0LCJleHAiOjE3NDAzODEwNzR9.LMMSY7EoQQQ3kvDk2j6tBhHYkbtnG-9bqIqDl9EA6g0

### Popular Services
GET http://localhost:3000/api/services/popular

##### BOOKING ROUTES #####
### Make a Booking
POST http://localhost:3000/api/bookings/1   # pass service id to be booked.
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MzEzOTY2LCJleHAiOjE3NDA5MDU5NjZ9.7RzpOvGGBYJTars4YJ-RotObGypZZtO245v-h4TOsGs

### Get all bookings
GET http://localhost:3000/api/bookings

### Get bookings of a service
GET http://localhost:3000/api/bookings?service_id=1

### Get booking by id
GET http://localhost:3000/api/bookings?booking_id=1

### Update a booking
PUT http://localhost:3000/api/bookings/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzM3ODE0MTY0LCJleHAiOjE3NDA0MDYxNjR9.d3IpXlnnof6gLFU_-SEYrLXEpUeRXiKAIBrKc1t-viM
Content-Type: application/json

{
    "status": "completed"
}

### Delete a booking
DELETE http://localhost:3000/api/bookings/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzM3ODE0MTY0LCJleHAiOjE3NDA0MDYxNjR9.d3IpXlnnof6gLFU_-SEYrLXEpUeRXiKAIBrKc1t-viM


##### MESSAGE ROUTES #####
### Send a message as User
POST http://localhost:3000/api/messages/user#send message as user to provider
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MTI2ODYxLCJleHAiOjE3NDA3MTg4NjF9.uLFyzb8EdSvaqExO1LW_eaRdV6obbiymgLAdih6O0sg
Content-Type: application/json

{
    "provider_id": 1,
    "message": "hey provider...."
}

### Send a message as provider
POST http://localhost:3000/api/messages/provider#send message as provider to user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MTI2NjU0LCJleHAiOjE3NDA3MTg2NTR9.YQOcZkKx8UkkRnReDcrlsYtxWbK62O14th37-YBhbpI
Content-Type: application/json

{
    "user_id": 1,
    "message": "Hi dear user ..."
}

### Get a chat
GET http://localhost:3000/api/messages/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MTI2ODYxLCJleHAiOjE3NDA3MTg4NjF9.uLFyzb8EdSvaqExO1LW_eaRdV6obbiymgLAdih6O0sg
Content-Type: application/json

{
    "user_id": 1,
    "provider_id": 1
}

### Delete a message
DELETE http://localhost:3000/api/messages/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MTI2ODYxLCJleHAiOjE3NDA3MTg4NjF9.uLFyzb8EdSvaqExO1LW_eaRdV6obbiymgLAdih6O0sg


##### ADMIN ROUTES #####
