### Testing Server Awaekness
GET http://localhost:3000/

##### USER ROUTES #####
### Create User
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name": "Rabin Gautam",
    "phone": "1234567890",
    "password": "password"
}

### Login User
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "phone": "1234567890",
    "password": "password"
}

### Get All Users
GET http://localhost:3000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MzEzOTY2LCJleHAiOjE3NDA5MDU5NjZ9.7RzpOvGGBYJTars4YJ-RotObGypZZtO245v-h4TOsGs

### Get User By Id
GET http://localhost:3000/api/users/1

### Update User Profile Picture only
PUT http://localhost:3000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3Mzg3MzI0ODMsImV4cCI6MTc0MTMyNDQ4M30.qPwO_y-w3__OKEiljdJBy0XMtsR1nvs3Qc431lxNX7I
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="userProfile"; filename="profile.jpg"
Content-Type: image/jpeg

< C:/Users/USER/Downloads/pp1.jpg
--boundary--

### Update User Profile
PUT http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM4NDI0NDk3LCJleHAiOjE3NDEwMTY0OTd9.YurtYZtBJYU3NqtJ8366bgHpw_Uvw16Bl6Nwwu4ZMks
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Rabin Gautam
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="phone"
Content-Type: text/plain

1234567890
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lat"
Content-Type: text/plain

23.455
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lon"
Content-Type: text/plain

45.678
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="userProfile"; filename="profile.jpg"
Content-Type: image/jpeg

< C:\Users\USER\Downloads\pp1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get profile picture of user
GET http://localhost:3000/uploads/userProfile-1738424524002.jpg

### Delete User
DELETE http://localhost:3000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM3MjEzMDQ2LCJleHAiOjE3Mzk4MDUwNDZ9.lrk3pn8KMlx6pELLvx2zU7XOWDs1V7zmiMLlwTvYVW0

##### PROVIDER ROUTES #####
### Create Provider
POST http://localhost:3000/api/providers/register
Content-Type: application/json

{
    "name": "Subash ",
    "phone": "1231234",
    "password": "123"
}

### Login Provider
POST http://localhost:3000/api/providers/login
Content-Type: application/json

{
    "phone": "1231234",
    "password": "123"
}

### Get All Providers
GET http://localhost:3000/api/providers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzM4NzMyNjEzLCJleHAiOjE3NDEzMjQ2MTN9.QUeh7QsoHs9zvdQRJoVfnQ2KElZt2lLD1ZQ0vct0kbQ

### Get Provider By Id
GET http://localhost:3000/api/providers/1

### Update Provider Profile Picture
PUT http://localhost:3000/api/providers/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM4NjQ0MTYyLCJleHAiOjE3NDEyMzYxNjJ9.ANiRBAD1g__zVYGJQWj_oRkpRsWDSX7VJvFpO1EQNSA
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="ProviderProfile"; filename="profile.jpg"
Content-Type: image/jpeg

< "C:\Users\joshi\Downloads\cleanings.jpg"
------boundary--

### Update Provider Profile Document
PUT http://localhost:3000/api/providers/document
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzM4NzMyNjEzLCJleHAiOjE3NDEzMjQ2MTN9.QUeh7QsoHs9zvdQRJoVfnQ2KElZt2lLD1ZQ0vct0kbQ
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="ProviderDocument"; filename="document.jpg"
Content-Type: image/jpeg

< C:\Users\USER\Downloads\pp1.jpg
------boundary--

### Update Provider (can remove any fields if not subjected to update
PUT http://localhost:3000/api/providers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzM4NzMyNjEzLCJleHAiOjE3NDEzMjQ2MTN9.QUeh7QsoHs9zvdQRJoVfnQ2KElZt2lLD1ZQ0vct0kbQ

{
    "name": "Nabin Sah",
    "phone": "1231234",
    "email": "sth@example.com",
    "ratePerHr": 450,
    "address": "Seti Bagar, Lamachaur",
    "city": "Pokhara",
    "lat": 40.7128,
    "lon": -74.0060,
    "bio": "Experienced service provider."
}

### Get profile picture or docunet of provider, or even of user or services
GET http://localhost:3000/uploads/ProviderDocument-1738645671367.jpg
# remove file name by profile or decoment url

### Delete Provider
DELETE http://localhost:3000/api/providers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzM4NjQ3MjQ3LCJleHAiOjE3NDEyMzkyNDd9.Nyh3YDCdU0W1fA-jjrjwvJXSBJkXLyaWzeGEWsP82hk

##### SERVICE CATEGORY ROUTES #####
### Create a category (Admin)
POST http://localhost:3000/api/categories
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Plumbing
------boundary
Content-Disposition: form-data; name="CategoryImage"; filename="category.jpg"
Content-Type: image/jpeg

< C:\Users\joshi\Downloads\cleanings.jpg
------boundary--

### Get all categories
GET http://localhost:3000/api/categories

### Update a category (Admin)
PUT http://localhost:3000/api/categories/4
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Repaiers
------boundary
Content-Disposition: form-data; name="CategoryImage"; filename="category.jpg"
Content-Type: image/jpeg

< C:\Users\joshi\Downloads\maintenance.jpg
------boundary--

### Delte Service Category (Admin)
DELETE http://localhost:3000/api/categories/4


##### SERVICE ROUTES #####
### Create Service (Admin)
POST http://localhost:3000/api/services
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM4NzMwMjQwLCJleHAiOjE3NDEzMjIyNDB9.65kkfU4MCeu76LdpMqFZUR2RQhoerjY2ZqzWY5tlZNU
Content-Type: application/json

{
    "categoryId": 1,
    "name": "Furniture Repair",
    "description": "Repair table, bed, chair, door etc of you home..",
    "minimumCharge": 300,
    "avgRatePerHr": 300
}

### Get all services
GET http://localhost:3000/api/services

### Get a service
GET http://localhost:3000/api/services/1

### Update a service image
PUT http://localhost:3000/api/services/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM4NzQyOTU5LCJleHAiOjE3NDEzMzQ5NTl9.DPv-1Pv5vC36iuu8xEDNDpRfilkACRoeLhhkc6tJLQo
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="serviceImg"; filename="profile.jpg"
Content-Type: image/jpeg

< C:\Users\USER\Downloads\pp1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Update a service
PUT http://localhost:3000/api/services/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3MjIwODM2LCJleHAiOjE3Mzk4MTI4MzZ9._X6yFsH1Sr6V2A6bOt_bwBYA9z1HiPrPlwx5ZSkpLis
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categoryId"
Content-Type: text/plain

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Plumbing
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"
Content-Type: text/plain

The reliable plumbing service around lamachaur.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="minimumCharge"
Content-Type: text/plain

200
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="type"
Content-Type: text/plain

plumbing
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="serviceImg"; filename="profile.jpg"
Content-Type: image/jpeg

< C:\Users\USER\Downloads\pp1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Delete a service
DELETE http://localhost:3000/api/services/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM3Nzg5MDc0LCJleHAiOjE3NDAzODEwNzR9.LMMSY7EoQQQ3kvDk2j6tBhHYkbtnG-9bqIqDl9EA6g0

### Popular Services
GET http://localhost:3000/api/services/popular


##### PROVIDER SERVICE ROUTES #####
### Link provider to a service
PUT http://localhost:3000/api/providerServices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzM4NzQ2MDAyLCJleHAiOjE3NDEzMzgwMDJ9.zYx8WC5q6XV_AOUt9MlnWntajZbg09gz7jPfkr3pq8I
Content-Type: application/json

{
    "serviceId":3
}

### Unlink provider to a service
DELETE http://localhost:3000/api/providerServices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzM4NzQ2MDAyLCJleHAiOjE3NDEzMzgwMDJ9.zYx8WC5q6XV_AOUt9MlnWntajZbg09gz7jPfkr3pq8I
Content-Type: application/json

{
    "serviceId":3
}

### Get providers of a service
GET http://localhost:3000/api/providerServices/providers/3

### Get services of a provider
GET http://localhost:3000/api/providerServices/services/2

##### BOOKING ROUTES #####
### /backend/requests/booking.rest maa xan

##### MESSAGE ROUTES #####
### Send a message as User
POST http://localhost:3000/api/messages#send message as user to provider
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3Mzg4MjQyNDksImV4cCI6MTc0MTQxNjI0OX0.tFOoQ5soARjCO_z4tpKuCqcoMsYH4h22h2TENMCI0QE
Content-Type: application/json

{
    "providerId": 1,
    "message": "hey provider...."
}

### Send a message as provider
POST http://localhost:3000/api/messages#send message as provider to user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzM4ODI0NTE4LCJleHAiOjE3NDE0MTY1MTh9.JfETa5_KidkJA64wBJlHfiwsjFJxwXzJiuCACtimigg
Content-Type: application/json

{
    "userId": 1,
    "message": "Hi dear user ..."
}

### Get a chat
GET http://localhost:3000/api/messages/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3Mzg4MjQyNDksImV4cCI6MTc0MTQxNjI0OX0.tFOoQ5soARjCO_z4tpKuCqcoMsYH4h22h2TENMCI0QE
Content-Type: application/json

{
    "userId": 1,
    "providerId": 1
}

### Delete a message
DELETE http://localhost:3000/api/messages/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MTI2ODYxLCJleHAiOjE3NDA3MTg4NjF9.uLFyzb8EdSvaqExO1LW_eaRdV6obbiymgLAdih6O0sg


##### ADMIN ROUTES #####
### Create Admin
POST http://localhost:3000/api/admin
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

###  Admin Login
POST http://localhost:3000/api/admin/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

##### TEST #####