### Create Admin
POST http://localhost:3000/api/admin
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

###  Admin Login
POST http://localhost:3000/api/admin/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}