### Create Admin
POST http://localhost:3000/api/admin
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

###  Admin Login
POST http://localhost:3000/api/admin/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

### Dashboard Stats
GET http://localhost:3000/api/admin/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ2MzM5NjQ0LCJleHAiOjE3NDg5MzE2NDR9.WpVGFe6Ow5LEEVMucRbOaHtlt49A_DHo-htdSgs9JKo

### Review Document
PUT http://localhost:3000/api/admin/review
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ2MzM5NjQ0LCJleHAiOjE3NDg5MzE2NDR9.WpVGFe6Ow5LEEVMucRbOaHtlt49A_DHo-htdSgs9JKo
Content-Type: application/json

{
    "documentId":4,
    "status":"rejected",
    "comment":"Document is not clear"
}