##### BOOKING ROUTES #####
### Make a Booking
POST http://localhost:3000/api/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc0Nzg5MjYsImV4cCI6MTc1MDA3MDkyNn0.Bhgf782fhW0iippB0M0xg-_6y0iomUwlKokFoq2GmQw
Content-Type: application/json

{
    "providerId":1,
    "serviceId":2,
    "scheduledDate":"2025-02-06T14:30:00+05:46",
    "amount": 1223.345,
    "address":"madhyam padh bahir",
    "city":"pokhara",
    "lat": 56.789,
    "lon": 89.123
}
#for random booking providerId is not required

### Get all bookings
GET http://localhost:3000/api/bookings

###* Get bookings with different filters
GET http://localhost:3000/api/bookings?paymentStatus=paid

# Available Filters for bookings:
        userId, serviceId, providerId, bookingId, bookingStatus,
minAmount, maxAmount, minRating, maxRating, bookingAfter, bookingBefore, address, city, lat, lon

### Update a booking
PUT http://localhost:3000/api/bookings/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc1MDAzNzIsImV4cCI6MTc1MDA5MjM3Mn0.Vf0i80TILqkd2SwbAc7xXpIjPq5FrnmX413raZjhrUw
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzQ3NTAxNzYyLCJleHAiOjE3NTAwOTM3NjJ9.VsDDfJWcgwYAZEMCfNME8wwd3rnM0LyA4sRkMbnEj5g
Content-Type: application/json

{
    "bookingStatus": "completed"
}
# Fields can be updated : scheduledDate, bookingStatus, paymentStatus, amount, rating, address, city, lat, lon,
# only user can set rating and scheduleDate


### Delete a booking
DELETE http://localhost:3000/api/bookings/29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6InVzZXIiLCJpYXQiOjE3NDY5NDg1MTcsImV4cCI6MTc0OTU0MDUxN30.S9IV91N8rrYjxb8iUlSfFbnE6HIoW_dEcXg2Jti7UuE
