##### BOOKING ROUTES #####
### Make a Booking
POST http://localhost:3000/api/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDY0MTk5NTIsImV4cCI6MTc0OTAxMTk1Mn0.2Gk9V0ksxcYOMszl0SKmEsk80YqUu3sxXNkjekP_mjI
Content-Type: application/json

{
    "providerId":12,
    "serviceId":5,
    "scheduledDate":"2025-02-06T14:30:00+05:45",
    "amount": 1223.345,
    "address":"madhyam padh bhaitra",
    "city":"pokhara",
    "lat": 56.789,
    "lon": 89.123
}
#for random booking providerId is not required

### Get all bookings
GET http://localhost:3000/api/bookings

###* Get bookings with different filters
GET http://localhost:3000/api/bookings?userId=1

### Available Filters for bookings:
        userId, serviceId, providerId, bookingId, bookingStatus,
minAmount, maxAmount, minRating, maxRating, bookingAfter, bookingBefore, address, city, lat, lon

### Update a booking
PUT http://localhost:3000/api/bookings/20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsInJvbGUiOiJwcm92aWRlciIsImlhdCI6MTc0NzIxOTgxMywiZXhwIjoxNzQ5ODExODEzfQ.F0kcA1PZjSm_neQfnsHvppaYjoSdx2nBFiEyuswaf5g
Content-Type: application/json

{
    "bookingStatus": "completed",
    "amount":1253.5,
    "paymentStatus":"paid",
    "rating":5,
    "address": "khause",
    "lat": 45.5776,
    "lon": 54.464 
}
# only user can set rating and scheduleDate

### Delete a booking
DELETE http://localhost:3000/api/bookings/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6InVzZXIiLCJpYXQiOjE3NDY5NDg1MTcsImV4cCI6MTc0OTU0MDUxN30.S9IV91N8rrYjxb8iUlSfFbnE6HIoW_dEcXg2Jti7UuE
