### Send a message as User
POST http://localhost:3000/api/messages#send message as user to provider
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc1NDE2MTAsImV4cCI6MTc1MDEzMzYxMH0.Jvx7N90Z0Z-YPdMwqDlRfDswwrvz1dYJOr6hUpQjKFE
Content-Type: application/json

{
    "providerId": 1,
    "message": "5 baje tira jasari ni aaonu talai hanna"
}

### Send a message as provider
POST http://localhost:3000/api/messages#send message as provider to user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzQ3NTQ5NDk2LCJleHAiOjE3NTAxNDE0OTZ9.Hm1ipOrpOH0XYh3xr6acmT8XUGQ6LGjbroABQVaRMj0
Content-Type: application/json

{
    "userId": 1,
    "message": "ok i will arrive as soon as possible 😊"
}

### Get a chat
GET http://localhost:3000/api/messages/chat?providerId=1&userId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc1NDE2MTAsImV4cCI6MTc1MDEzMzYxMH0.Jvx7N90Z0Z-YPdMwqDlRfDswwrvz1dYJOr6hUpQjKFE

### Delete a message
DELETE http://localhost:3000/api/messages/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MTI2ODYxLCJleHAiOjE3NDA3MTg4NjF9.uLFyzb8EdSvaqExO1LW_eaRdV6obbiymgLAdih6O0sg


### Chat List
GET http://localhost:3000/api/messages/chatList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc1NDE2MTAsImV4cCI6MTc1MDEzMzYxMH0.Jvx7N90Z0Z-YPdMwqDlRfDswwrvz1dYJOr6hUpQjKFE