### Send a message as User
POST http://localhost:3000/api/messages#send message as user to provider
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc1NDE2MTAsImV4cCI6MTc1MDEzMzYxMH0.Jvx7N90Z0Z-YPdMwqDlRfDswwrvz1dYJOr6hUpQjKFE
Content-Type: application/json

{
    "providerId": 1,
    "message": "hey provider...."
}

### Send a message as provider
POST http://localhost:3000/api/messages#send message as provider to user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzQ3NTQxNjcxLCJleHAiOjE3NTAxMzM2NzF9.hGZ6F8a-l3PUKno4skv1W5cnZTWUpill1RxLopAKHPA
Content-Type: application/json

{
    "userId": 1,
    "message": "Hi dear user ..."
}

### Get a chat
GET http://localhost:3000/api/messages/chat?userId=1&providerId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzQ3NTQyNzM2LCJleHAiOjE3NTAxMzQ3MzZ9.1YrMTIf2E6g7WvvtIopzL5Jowqstdk9J3qQyXs5paqY

### Delete a message
DELETE http://localhost:3000/api/messages/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MTI2ODYxLCJleHAiOjE3NDA3MTg4NjF9.uLFyzb8EdSvaqExO1LW_eaRdV6obbiymgLAdih6O0sg
