### Create Notification
POST http://localhost:3000/api/notifications
Content-Type: application/json

{
  "userId": 1,
  # "ProviderId": 3, 
  "title": "New booking", 
  "body":"You got a new booking"
}

### Get Notifications
GET http://localhost:3000/api/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzQ3NTEyMzU4LCJleHAiOjE3NTAxMDQzNTh9.YhkTHYPeAjZrAQfgJqHNKwAy6aVNog1_MlTBIEK_D1k

### Mark Notification as read
PUT http://localhost:3000/api/notifications/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzQ3NTEyMzU4LCJleHAiOjE3NTAxMDQzNTh9.YhkTHYPeAjZrAQfgJqHNKwAy6aVNog1_MlTBIEK_D1k
### Delete Notification
DELETE http://localhost:3000/api/notifications/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzQ3NTEyMzU4LCJleHAiOjE3NTAxMDQzNTh9.YhkTHYPeAjZrAQfgJqHNKwAy6aVNog1_MlTBIEK_D1k