### Link provider to a service
PUT http://localhost:3000/api/providerServices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInJvbGUiOiJwcm92aWRlciIsImlhdCI6MTc0MjAyOTc5MSwiZXhwIjoxNzQ0NjIxNzkxfQ.vz68u0bd-_VN8xjkvhxi5KtUEhNWmusF61r6fajljCM
Content-Type: application/json

{
    "serviceId":[2,3,4]
}

### Unlink provider to a service
DELETE http://localhost:3000/api/providerServices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInJvbGUiOiJwcm92aWRlciIsImlhdCI6MTc0MjAyOTI1NSwiZXhwIjoxNzQ0NjIxMjU1fQ.zgtvEZRMU37qYZrOaBITWy8X4oDtOYujlYSQT6W3gdY
Content-Type: application/json

{
    "serviceId":2
}

### Get providers of a service
GET http://localhost:3000/api/providerServices/providers/1

### Get services of a provider
GET http://localhost:3000/api/providerServices/services/12