### Create Provider
POST http://localhost:3000/api/providers/register
Content-Type: application/json

{
    "name": "Subash ",
    "phone": "9869",
    "email": "s@gmail.com",
    "password": "password"
}

### Login Provider
POST http://localhost:3000/api/providers/login
Content-Type: application/json

{
    "phone": "1234567890",
    "password": "password"
}

### Get All Providers
GET http://localhost:3000/api/providers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzM4NzMyNjEzLCJleHAiOjE3NDEzMjQ2MTN9.QUeh7QsoHs9zvdQRJoVfnQ2KElZt2lLD1ZQ0vct0kbQ

### Get Provider By Id
GET http://localhost:3000/api/providers/1

### Update Provider Profile Picture
PUT http://localhost:3000/api/providers/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsInJvbGUiOiJwcm92aWRlciIsImlhdCI6MTc0MTg1NzExMCwiZXhwIjoxNzQ0NDQ5MTEwfQ.ynuGQUBXtkeo_TjuZ1iOCu_oCCGuSCefCu1PgXs75Q8
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="ProviderProfile"; filename="profile.jpg"
Content-Type: image/jpeg

< C:\Users\joshi\Downloads\cleanings.jpg
------boundary--

### Update Provider Document Image
PUT http://localhost:3000/api/providers/document
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInJvbGUiOiJwcm92aWRlciIsImlhdCI6MTc0NzEyNDYzOSwiZXhwIjoxNzQ5NzE2NjM5fQ.RBQo9xdSFQBLXgA0LEX8MwGZvR4L_0_SZ4pbSJZiUzI
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="ProviderDocument"; filename="document.jpg"
Content-Type: image/jpeg

< C:\Users\joshi\Downloads\Forgot Password.png
------boundary--

### Update Provider (Can remove any fields if not subjected to update)
PUT http://localhost:3000/api/providers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3NTc3ODYwLCJleHAiOjE3NTAxNjk4NjB9.OA5w9qiMAjZ2ZIasqScjKFX7EHExr0KtnMlc1aC1c1U
Content-Type: application/json

{
    "verificationStatus": "verified"
}

### Get Docuemnt(/s) details of Provider
GET http://localhost:3000/api/providers/document
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInJvbGUiOiJwcm92aWRlciIsImlhdCI6MTc0NzEyNDYzOSwiZXhwIjoxNzQ5NzE2NjM5fQ.RBQo9xdSFQBLXgA0LEX8MwGZvR4L_0_SZ4pbSJZiUzI
### filters : id, providerId, status, uploadedAt, lastReview, comment

### Get profile picture or document of provider, or even of user or services
GET http://localhost:3000/uploads/ProviderDocument-1738645671367.jpg
# remove file name by profile or decoment url

### Delete Provider
DELETE http://localhost:3000/api/providers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzM4NjQ3MjQ3LCJleHAiOjE3NDEyMzkyNDd9.Nyh3YDCdU0W1fA-jjrjwvJXSBJkXLyaWzeGEWsP82hk

### Verify Provider (Admin)
PUT http://localhost:3000/api/providers/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM5NzM0MTM3LCJleHAiOjE3NDIzMjYxMzd9.sPkn-7GhX2Q5s6BBb5HhN4J1TRRLtEaL9hK62LuDAZk
Content-Type: application/json

{
    "providerId": 1,
    "status": "verified"
}