### Link provider to a service
PUT http://localhost:3000/api/providerServices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzQ3NTkyMDY3LCJleHAiOjE3NTAxODQwNjd9.k3ORmtsFIlJL7TzJ00Zn1m3dQwmmss0ZGEprdYqyg1o
Content-Type: application/json

{
    "serviceId":[8,14]
}

### Unlink provider to a service
DELETE http://localhost:3000/api/providerServices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInJvbGUiOiJwcm92aWRlciIsImlhdCI6MTc0MjAyOTI1NSwiZXhwIjoxNzQ0NjIxMjU1fQ.zgtvEZRMU37qYZrOaBITWy8X4oDtOYujlYSQT6W3gdY
Content-Type: application/json

{
    "serviceId":2
}

### Get providers of a service
GET http://localhost:3000/api/providerServices/providers/3

### Get services of a provider
GET http://localhost:3000/api/providerServices/services/3