### Create Service (Admin)
POST http://localhost:3000/api/services
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM4NzMwMjQwLCJleHAiOjE3NDEzMjIyNDB9.65kkfU4MCeu76LdpMqFZUR2RQhoerjY2ZqzWY5tlZNU
Content-Type: application/json

{
    "categoryId": 1,
    "name": "Furniture Repair",
    "description": "Repair table, bed, chair, door etc of you home..",
    "minimumCharge": 300,
    "avgRatePerHr": 300
}

### Get all services
GET http://localhost:3000/api/services

### Get a service
GET http://localhost:3000/api/services/1

### Update a service image
PUT http://localhost:3000/api/services/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM4NzQyOTU5LCJleHAiOjE3NDEzMzQ5NTl9.DPv-1Pv5vC36iuu8xEDNDpRfilkACRoeLhhkc6tJLQo
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="serviceImg"; filename="profile.jpg"
Content-Type: image/jpeg

< C:\Users\USER\Downloads\pp1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Update a service
PUT http://localhost:3000/api/services/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3MjIwODM2LCJleHAiOjE3Mzk4MTI4MzZ9._X6yFsH1Sr6V2A6bOt_bwBYA9z1HiPrPlwx5ZSkpLis
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categoryId"
Content-Type: text/plain

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Plumbing
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"
Content-Type: text/plain

The reliable plumbing service around lamachaur.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="minimumCharge"
Content-Type: text/plain

200
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="type"
Content-Type: text/plain

plumbing
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="serviceImg"; filename="profile.jpg"
Content-Type: image/jpeg

< C:\Users\USER\Downloads\pp1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Delete a service
DELETE http://localhost:3000/api/services/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM3Nzg5MDc0LCJleHAiOjE3NDAzODEwNzR9.LMMSY7EoQQQ3kvDk2j6tBhHYkbtnG-9bqIqDl9EA6g0

### Popular Services
GET http://localhost:3000/api/services/popular
