### Create User
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name": "Rabin Gautam",
    "phone": "0000",
    "password": "123"
}

### Login User
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "phone": "12345",
    "password": "asdf"
}

### Set address
PUT http://localhost:3000/api/users/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc2NTU3NDAsImV4cCI6MTc1MDI0Nzc0MH0.TM4csubfwLTTf3psTeWIDXY3XqN-7UQBGWfbIyS9N9w
Content-Type: "application/json"

{
    "lat": 21.23424,
    "lon": 12.344
}


### Get All Users
GET http://localhost:3000/api/users/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MzEzOTY2LCJleHAiOjE3NDA5MDU5NjZ9.7RzpOvGGBYJTars4YJ-RotObGypZZtO245v-h4TOsGs

### Get User By Id
GET http://localhost:3000/api/users/9

### Update User Profile Picture only
PUT http://localhost:3000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InVzZXIiLCJpYXQiOjE3MzkwMjkzODAsImV4cCI6MTc0MTYyMTM4MH0.CAhNOhHNCxL4407YVNYmduCaqu5gSvGk2HPGTNJPnqM
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="userProfile"; filename="profile.jpg"
Content-Type: image/jpeg

< C:/Users/USER/Downloads/pp1.jpg
--boundary--

### Update User Profile along with profile picture
PUT http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc1NjY4NjksImV4cCI6MTc1MDE1ODg2OX0.zLo2zBlafam4eUiQMQQ4Eg3gAyO8ZzWaSy152s0H4eg
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Rabin Gautam
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="phone"
Content-Type: text/plain

1234567890
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lat"
Content-Type: text/plain

23.455
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lon"
Content-Type: text/plain

45.678
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="userProfile"; filename="profile.jpg"
Content-Type: image/jpeg

< C:\Users\USER\Downloads\pp1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get profile picture of user
GET http://localhost:3000/uploads/userProfile-1739029396298.jpg

### Delete User
DELETE http://localhost:3000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6InVzZXIiLCJpYXQiOjE3NDc1Njc5ODUsImV4cCI6MTc1MDE1OTk4NX0.F4Ql_MVAKWJLc_ADJsXSFEBNhI5iV_zfsttPRMbhQZo